spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/quartz?characterEncoding=utf-8
    username: root
    password: root
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: never